export const PREFIJOS = [
  // 1 — Galvanizado carbono
  { p: '1CO', d: 'Codo/Curva galvanizado' },
  { p: '1CA', d: 'Caño galvanizado' },
  { p: '1TE', d: 'Tee galvanizada' },
  { p: '1NI', d: 'Niple galvanizado' },
  { p: '1CU', d: 'Cupla / Unión galvanizada' },
  { p: '1TA', d: 'Tapón galvanizado' },
  { p: '1BU', d: 'Buje galvanizado' },
  { p: '1RE', d: 'Reducción galvanizada' },
  { p: '1BR', d: 'Brida galvanizada' },
  { p: '1VR', d: 'Accesorios varios galvanizado' },
  // 2 — Para soldar
  { p: '2CO', d: 'Codo/Curva para soldar' },
  { p: '2CA', d: 'Caño para soldar' },
  { p: '2TE', d: 'Tee para soldar' },
  { p: '2NI', d: 'Niple para soldar' },
  { p: '2TA', d: 'Tapón para soldar' },
  { p: '2BR', d: 'Brida para soldar' },
  { p: '2RE', d: 'Reducción para soldar' },
  { p: '2VR', d: 'Accesorios varios para soldar' },
  // 3 — Epoxi
  { p: '3CO', d: 'Codo/Curva epoxi' },
  { p: '3CA', d: 'Caño epoxi' },
  { p: '3TE', d: 'Tee epoxi' },
  { p: '3NI', d: 'Niple epoxi' },
  { p: '3CU', d: 'Cupla epoxi' },
  { p: '3TA', d: 'Tapón epoxi' },
  { p: '3RE', d: 'Reducción epoxi' },
  { p: '3VR', d: 'Accesorios varios epoxi' },
  // 4 — Válvulas (por material)
  { p: '401', d: 'Válvula acero inox' },
  { p: '402', d: 'Válvula bronce' },
  { p: '403', d: 'Válvula hierro' },
  { p: '404', d: 'Válvula aluminio' },
  { p: '406', d: 'Válvula PVC' },
  { p: '407', d: 'Válvula polipropileno' },
  { p: '408', d: 'Válvula termofusión' },
  { p: '409', d: 'Válvula polietileno' },
  { p: '411', d: 'Válvula metálica' },
  // 6 — PVC (presión y cloacal unificados)
  { p: '6CO', d: 'Codo/Curva PVC' },
  { p: '6CV', d: 'Curva PVC' },
  { p: '6CA', d: 'Caño PVC' },
  { p: '6TE', d: 'Tee / Ramal PVC' },
  { p: '6CU', d: 'Cupla / Unión PVC' },
  { p: '6TA', d: 'Tapón PVC' },
  { p: '6RE', d: 'Reducción PVC' },
  { p: '6LV', d: 'Llave PVC' },
  { p: '6UN', d: 'Unión PVC' },
  { p: '6VR', d: 'Accesorios varios PVC' },
  // 7 — Polipropileno (PP)
  { p: '7CO', d: 'Codo/Curva polipropileno' },
  { p: '7CA', d: 'Caño polipropileno' },
  { p: '7TE', d: 'Tee polipropileno' },
  { p: '7NI', d: 'Niple polipropileno' },
  { p: '7CU', d: 'Cupla / Unión polipropileno' },
  { p: '7TA', d: 'Tapón polipropileno' },
  { p: '7RE', d: 'Reducción polipropileno' },
  { p: '7BR', d: 'Brida polipropileno' },
  { p: '7MO', d: 'Montura polipropileno' },
  { p: '7VR', d: 'Accesorios varios polipropileno' },
  // I — Termofusión (PPR / PE)
  { p: 'ICO', d: 'Codo/Curva termofusión' },
  { p: 'ICA', d: 'Caño termofusión' },
  { p: 'ITE', d: 'Tee termofusión' },
  { p: 'ICU', d: 'Cupla termofusión' },
  { p: 'ITA', d: 'Tapón termofusión' },
  { p: 'IRE', d: 'Reducción termofusión' },
  { p: 'IUN', d: 'Unión doble termofusión' },
  { p: 'ILV', d: 'Llave termofusión' },
  { p: 'IMO', d: 'Montura termofusión' },
  { p: 'IVR', d: 'Accesorios varios termofusión' },
  // L — Electrofusión (HDPE / PE)
  { p: 'LCO', d: 'Codo/Curva electrofusión' },
  { p: 'LCA', d: 'Caño electrofusión' },
  { p: 'LTE', d: 'Tee electrofusión' },
  { p: 'LCU', d: 'Cupla electrofusión' },
  { p: 'LTA', d: 'Tapón electrofusión' },
  { p: 'LRE', d: 'Reducción electrofusión' },
  { p: 'LSA', d: 'Silleta / abrazadera electrofusión' },
  { p: 'LUN', d: 'Unión electrofusión' },
  { p: 'LVR', d: 'Accesorios varios electrofusión' },
  // K — Inoxidable (piping)
  { p: 'KCO', d: 'Codo/Curva inoxidable' },
  { p: 'KCA', d: 'Caño inoxidable' },
  { p: 'KTE', d: 'Tee inoxidable' },
  { p: 'KNI', d: 'Niple inoxidable' },
  { p: 'KCU', d: 'Cupla inoxidable' },
  { p: 'KTA', d: 'Tapón inoxidable' },
  { p: 'KBR', d: 'Brida inoxidable' },
  { p: 'KRE', d: 'Reducción inoxidable' },
  { p: 'KVR', d: 'Accesorios varios inoxidable' },
  // D — Bronce (piping)
  { p: 'DCO', d: 'Codo/Curva bronce' },
  { p: 'DCA', d: 'Caño bronce' },
  { p: 'DTE', d: 'Tee bronce' },
  { p: 'DNI', d: 'Niple bronce' },
  { p: 'DCU', d: 'Cupla bronce' },
  { p: 'DTA', d: 'Tapón bronce' },
  { p: 'DBR', d: 'Brida bronce' },
  { p: 'DRE', d: 'Reducción bronce' },
  { p: 'DVR', d: 'Accesorios varios bronce' },
  // 5 — Bulonería / Ferretería
  { p: '5BL', d: 'Bulonería general' },
  { p: '5TU', d: 'Tuercas' },
  { p: '5AR', d: 'Arandelas' },
  { p: '5AC', d: 'Anclajes / Taco Fisher' },
  { p: '5RE', d: 'Regatones / Tapones' },
  { p: '5PF', d: 'Perfiles estructurales' },
  // 9 — Eléctrico
  { p: '9CA', d: 'Cables' },
  { p: '9CJ', d: 'Gabinetes / Tableros / Cajas' },
  { p: '9CD', d: 'Conduit / Caños eléctricos' },
  { p: '9TM', d: 'Terminales / Bornas' },
  { p: '9CT', d: 'Controles / PLC / Variadores' },
  { p: '9FU', d: 'Protecciones eléctricas' },
  { p: '9N0', d: 'Termomagneticas' },
  { p: '9IN', d: 'Instrumentación' },
  { p: '9LZ', d: 'Iluminación' },
  { p: '9TP', d: 'Tomas y fichas' },
  { p: '9GM', d: 'Guardamotores / Contactores' },
  { p: '9BN', d: 'Bandejas / Cablecanal' },
  { p: '9Z9', d: 'Fuentes / Transformadores' },
  { p: '9VR', d: 'Eléctrico varios' },
  // A — Bombas
  { p: 'ACF', d: 'Bombas centrífugas' },
  { p: 'ADS', d: 'Bombas dosificadoras' },
  { p: 'ASM', d: 'Bombas sumergibles' },
  { p: 'AAU', d: 'Bombas autocebantes' },
  { p: 'APR', d: 'Bombas peristálticas' },
  { p: 'AVN', d: 'Bombas de vacío' },
  { p: 'AAC', d: 'Accesorios de bombas' },
  { p: 'AVR', d: 'Bombas varios' },
  // B — Equipos mecánicos
  { p: 'BSP', d: 'Sopladores' },
  { p: 'BCM', d: 'Compresores' },
  { p: 'BMR', d: 'Motoreductores' },
  { p: 'BMT', d: 'Motores eléctricos' },
  { p: 'BVR', d: 'Equipos varios' },
  // C — Mangueras
  { p: 'CTF', d: 'Mangueras (rollo/tubo flex)' },
  { p: 'CAC', d: 'Accesorios mangueras' },
  { p: 'CMG', d: 'Mangueras (varios)' },
  // E — Chapas y metales
  { p: 'ELP', d: 'Chapas / Láminas' },
  { p: 'EIX', d: 'Inoxidable' },
  { p: 'EPM', d: 'Perfiles / Ángulos / Vigas' },
  { p: 'EPC', d: 'Piezas cortadas' },
  { p: 'ECA', d: 'Caños estructurales' },
  // F — Filtración
  { p: 'FBF', d: 'Bolsas filtrantes' },
  { p: 'FCF', d: 'Cartuchos filtrantes' },
  { p: 'FDF', d: 'Difusores' },
  { p: 'FCE', d: 'Filtros (varios)' },
  { p: 'FMO', d: 'Membranas ósmosis inversa' },
  // G — Tanques
  { p: 'GPL', d: 'Tanques plásticos' },
  { p: 'GFV', d: 'Fibra de vidrio' },
  { p: 'GMT', d: 'Tanques metálicos' },
  { p: 'GAC', d: 'Accesorios tanques' },
  // J — Mecánico / accesorios
  { p: 'JRO', d: 'Rodamientos' },
  { p: 'JCH', d: 'Chavetas' },
  { p: 'JRS', d: 'Resortes' },
  { p: 'JRU', d: 'Ruedas / Poleas' },
  { p: 'JAC', d: 'Acoplamientos' },
  { p: 'JFM', d: 'Fittings metálicos roscados' },
  { p: 'JEJ', d: 'Ejes / Bujes / Retenes' },
  { p: 'JPM', d: 'Platillos / Soporte mecánico' },
  { p: 'JTR', d: 'Transmisiones (cadenas, piñones)' },
  { p: 'JVR', d: 'Mecánico varios' },
  // N — Herramientas
  { p: 'NLV', d: 'Llaves / Destornilladores' },
  { p: 'NBR', d: 'Brocas / Machos de roscar' },
  { p: 'NDS', d: 'Discos de corte / amolar' },
  { p: 'NHM', d: 'Martillos / Herr. de golpe' },
  { p: 'NMC', d: 'Medición (cintas, niveles)' },
  { p: 'NES', d: 'Escaleras' },
  { p: 'NSP', d: 'Sopletes / Pistolas' },
  { p: 'NCT', d: 'Cuchillas / Trinchetas' },
  { p: 'NCL', d: 'Clamps / Prensas' },
  { p: 'NVR', d: 'Herramientas varios' },
  // O — Insumos
  { p: 'OLM', d: 'Limpieza' },
  { p: 'OPT', d: 'Pintura / Revestimientos' },
  { p: 'OSD', d: 'Soldadura' },
  { p: 'OAB', d: 'Abrasivos / Lijas' },
  { p: 'OSL', d: 'Selladores / Silicona / Teflón' },
  { p: 'OEM', d: 'Embalaje / Cinta / Film' },
  { p: 'OLI', d: 'Librería / Insumos de oficina' },
  { p: 'OVR', d: 'Insumos varios' },
  // Q — Productos Químicos
  { p: 'QCL', d: 'Cloro / Hipoclorito' },
  { p: 'QAC', d: 'Ácidos' },
  { p: 'QAL', d: 'Álcalis / Bases' },
  { p: 'QFL', d: 'Floculantes' },
  { p: 'QCO', d: 'Coagulantes' },
  { p: 'QAN', d: 'Antiincrustantes' },
  { p: 'QDS', d: 'Desinfectantes / Biocidas' },
  { p: 'QVR', d: 'Químicos varios' },
  // P — EPP
  { p: 'PRP', d: 'Ropa de trabajo' },
  { p: 'PRS', d: 'Respiradores' },
  { p: 'PVS', d: 'Protección visual' },
  { p: 'PCP', d: 'EPP general' },
]

export const FAM_NOMBRES = {
  '1':'Galvanizado carbono', '2':'Para soldar', '3':'Epoxi',
  '4':'Válvulas', '6':'PVC', '7':'Polipropileno (PP)',
  'I':'Termofusión (PPR / PE)', 'L':'Electrofusión (HDPE / PE)', 'K':'Inoxidable (piping)',
  'D':'Bronce (piping)',
  '5':'Bulonería / Ferretería', '9':'Eléctrico', 'A':'Bombas',
  'B':'Equipos mecánicos', 'C':'Mangueras', 'E':'Chapas y metales',
  'F':'Filtración', 'G':'Tanques', 'J':'Mecánico / Accesorios',
  'N':'Herramientas', 'O':'Insumos', 'Q':'Productos Químicos', 'P':'EPP',
}
