export const PREFIJOS = [
  // 1 — Galvanizado carbono
  { p: '1CO', d: 'Codo/Curva galvanizado' },
  { p: '1CA', d: 'Caño galvanizado' },
  { p: '1TE', d: 'Tee galvanizada' },
  { p: '1NI', d: 'Niple galvanizado' },
  { p: '1CU', d: 'Cupla / Unión galvanizada' },
  { p: '1TA', d: 'Tapón galvanizado' },
  { p: '1BU', d: 'Buje galvanizado' },
  { p: '1RE', d: 'Reducción galvanizada' },
  { p: '1BR', d: 'Brida galvanizada' },
  // 2 — Para soldar
  { p: '2CO', d: 'Codo/Curva para soldar' },
  { p: '2CA', d: 'Caño para soldar' },
  { p: '2TE', d: 'Tee para soldar' },
  { p: '2NI', d: 'Niple para soldar' },
  { p: '2TA', d: 'Tapón para soldar' },
  { p: '2BR', d: 'Brida para soldar' },
  { p: '2RE', d: 'Reducción para soldar' },
  // 3 — Epoxi
  { p: '3CO', d: 'Codo/Curva epoxi' },
  { p: '3CA', d: 'Caño epoxi' },
  { p: '3TE', d: 'Tee epoxi' },
  { p: '3NI', d: 'Niple epoxi' },
  { p: '3CU', d: 'Cupla epoxi' },
  { p: '3TA', d: 'Tapón epoxi' },
  { p: '3RE', d: 'Reducción epoxi' },
  // 4 — PVC presión
  { p: '4CO', d: 'Codo/Curva PVC presión' },
  { p: '4CA', d: 'Caño PVC presión' },
  { p: '4TE', d: 'Tee PVC presión' },
  { p: '4CU', d: 'Cupla PVC presión' },
  { p: '4TA', d: 'Tapón PVC presión' },
  { p: '4RE', d: 'Reducción PVC presión' },
  { p: '4LV', d: 'Llave PVC presión' },
  { p: '4UN', d: 'Unión PVC presión' },
  // 6 — PVC cloacal / desagüe
  { p: '6CO', d: 'Codo/Curva PVC cloacal' },
  { p: '6CV', d: 'Curva PVC cloacal' },
  { p: '6CA', d: 'Caño PVC cloacal' },
  { p: '6TE', d: 'Ramal / Tee PVC cloacal' },
  { p: '6CU', d: 'Cupla / Unión PVC cloacal' },
  { p: '6TA', d: 'Tapón PVC cloacal' },
  { p: '6RE', d: 'Reducción PVC cloacal' },
  // 7 — CPVC
  { p: '7CO', d: 'Codo/Curva CPVC' },
  { p: '7CA', d: 'Caño CPVC' },
  { p: '7TE', d: 'Tee CPVC' },
  { p: '7CU', d: 'Cupla CPVC' },
  { p: '7TA', d: 'Tapón CPVC' },
  { p: '7RE', d: 'Reducción CPVC' },
  { p: '7UN', d: 'Unión CPVC' },
  // I — Termofusión (PPR / PE)
  { p: 'ICO', d: 'Codo/Curva termofusión' },
  { p: 'ICA', d: 'Caño termofusión' },
  { p: 'ITE', d: 'Tee termofusión' },
  { p: 'ICU', d: 'Cupla termofusión' },
  { p: 'ITA', d: 'Tapón termofusión' },
  { p: 'IRE', d: 'Reducción termofusión' },
  { p: 'IUN', d: 'Unión doble termofusión' },
  { p: 'ILV', d: 'Llave termofusión' },
  { p: 'IMO', d: 'Montura termofusión' },
  // H — Polipropileno (PP)
  { p: 'HCO', d: 'Codo/Curva polipropileno' },
  { p: 'HCA', d: 'Caño polipropileno' },
  { p: 'HTE', d: 'Tee polipropileno' },
  { p: 'HNI', d: 'Niple polipropileno' },
  { p: 'HCU', d: 'Cupla / Unión polipropileno' },
  { p: 'HTA', d: 'Tapón polipropileno' },
  { p: 'HRE', d: 'Reducción polipropileno' },
  { p: 'HBR', d: 'Brida polipropileno' },
  { p: 'HMO', d: 'Montura polipropileno' },
  // L — Electrofusión (HDPE / PE)
  { p: 'LCO', d: 'Codo/Curva electrofusión' },
  { p: 'LCA', d: 'Caño electrofusión' },
  { p: 'LTE', d: 'Tee electrofusión' },
  { p: 'LCU', d: 'Cupla electrofusión' },
  { p: 'LTA', d: 'Tapón electrofusión' },
  { p: 'LRE', d: 'Reducción electrofusión' },
  { p: 'LSA', d: 'Silleta / abrazadera electrofusión' },
  { p: 'LUN', d: 'Unión electrofusión' },
  // K — Inoxidable (piping)
  { p: 'KCO', d: 'Codo/Curva inoxidable' },
  { p: 'KCA', d: 'Caño inoxidable' },
  { p: 'KTE', d: 'Tee inoxidable' },
  { p: 'KNI', d: 'Niple inoxidable' },
  { p: 'KCU', d: 'Cupla inoxidable' },
  { p: 'KTA', d: 'Tapón inoxidable' },
  { p: 'KBR', d: 'Brida inoxidable' },
  { p: 'KRE', d: 'Reducción inoxidable' },
  // 5 — Bulonería / Ferretería
  { p: '5BL', d: 'Bulonería general' },
  { p: '5TU', d: 'Tuercas' },
  { p: '5AR', d: 'Arandelas' },
  { p: '5AC', d: 'Anclajes / Taco Fisher' },
  { p: '5RE', d: 'Regatones / Tapones' },
  { p: '5PF', d: 'Perfiles estructurales' },
  // 9 — Eléctrico
  { p: '9CA', d: 'Cables' },
  { p: '9CJ', d: 'Gabinetes / Tableros / Cajas' },
  { p: '9CD', d: 'Conduit / Caños eléctricos' },
  { p: '9TM', d: 'Terminales / Bornas' },
  { p: '9CT', d: 'Controles / PLC / Variadores' },
  { p: '9FU', d: 'Protecciones eléctricas' },
  { p: '9N0', d: 'Termomagneticas' },
  { p: '9IN', d: 'Instrumentación' },
  { p: '9LZ', d: 'Iluminación' },
  { p: '9TP', d: 'Tomas y fichas' },
  { p: '9GM', d: 'Guardamotores / Contactores' },
  { p: '9BN', d: 'Bandejas / Cablecanal' },
  { p: '9Z9', d: 'Fuentes / Transformadores' },
  { p: '9VR', d: 'Eléctrico varios' },
  // A — Bombas
  { p: 'ACF', d: 'Bombas centrífugas' },
  { p: 'ADS', d: 'Bombas dosificadoras' },
  { p: 'ASM', d: 'Bombas sumergibles' },
  { p: 'AAU', d: 'Bombas autocebantes' },
  { p: 'APR', d: 'Bombas peristálticas' },
  { p: 'AVN', d: 'Bombas de vacío' },
  { p: 'AAC', d: 'Accesorios de bombas' },
  { p: 'AVR', d: 'Bombas varios' },
  // B — Equipos mecánicos
  { p: 'BSP', d: 'Sopladores' },
  { p: 'BCM', d: 'Compresores' },
  { p: 'BMR', d: 'Motoreductores' },
  { p: 'BMT', d: 'Motores eléctricos' },
  { p: 'BVR', d: 'Equipos varios' },
  // C — Mangueras
  { p: 'CTF', d: 'Mangueras (rollo/tubo flex)' },
  { p: 'CAC', d: 'Accesorios mangueras' },
  { p: 'CMG', d: 'Mangueras (varios)' },
  // E — Chapas y metales
  { p: 'ELP', d: 'Chapas / Láminas' },
  { p: 'EIX', d: 'Inoxidable' },
  { p: 'EPM', d: 'Perfiles / Ángulos / Vigas' },
  { p: 'EPC', d: 'Piezas cortadas' },
  { p: 'ECA', d: 'Caños estructurales' },
  // F — Filtración
  { p: 'FBF', d: 'Bolsas filtrantes' },
  { p: 'FCF', d: 'Cartuchos filtrantes' },
  { p: 'FDF', d: 'Difusores' },
  { p: 'FCE', d: 'Filtros (varios)' },
  // G — Tanques
  { p: 'GPL', d: 'Tanques plásticos' },
  { p: 'GFV', d: 'Fibra de vidrio' },
  { p: 'GMT', d: 'Tanques metálicos' },
  { p: 'GAC', d: 'Accesorios tanques' },
  // J — Mecánico / accesorios
  { p: 'JRO', d: 'Rodamientos' },
  { p: 'JCH', d: 'Chavetas' },
  { p: 'JRS', d: 'Resortes' },
  { p: 'JRU', d: 'Ruedas / Poleas' },
  { p: 'JAC', d: 'Acoplamientos' },
  { p: 'JFM', d: 'Fittings metálicos roscados' },
  { p: 'JEJ', d: 'Ejes / Bujes / Retenes' },
  { p: 'JPM', d: 'Platillos / Soporte mecánico' },
  { p: 'JTR', d: 'Transmisiones (cadenas, piñones)' },
  { p: 'JVR', d: 'Mecánico varios' },
  // N — Herramientas
  { p: 'NLV', d: 'Llaves / Destornilladores' },
  { p: 'NBR', d: 'Brocas / Machos de roscar' },
  { p: 'NDS', d: 'Discos de corte / amolar' },
  { p: 'NHM', d: 'Martillos / Herr. de golpe' },
  { p: 'NMC', d: 'Medición (cintas, niveles)' },
  { p: 'NES', d: 'Escaleras' },
  { p: 'NSP', d: 'Sopletes / Pistolas' },
  { p: 'NCT', d: 'Cuchillas / Trinchetas' },
  { p: 'NCL', d: 'Clamps / Prensas' },
  { p: 'NVR', d: 'Herramientas varios' },
  // O — Insumos
  { p: 'OLM', d: 'Limpieza' },
  { p: 'OPT', d: 'Pintura / Revestimientos' },
  { p: 'OSD', d: 'Soldadura' },
  { p: 'OAB', d: 'Abrasivos / Lijas' },
  { p: 'OSL', d: 'Selladores / Silicona / Teflón' },
  { p: 'OEM', d: 'Embalaje / Cinta / Film' },
  { p: 'OVR', d: 'Insumos varios' },
  // Q — Productos Químicos
  { p: 'QCL', d: 'Cloro / Hipoclorito' },
  { p: 'QAC', d: 'Ácidos' },
  { p: 'QAL', d: 'Álcalis / Bases' },
  { p: 'QFL', d: 'Floculantes' },
  { p: 'QCO', d: 'Coagulantes' },
  { p: 'QAN', d: 'Antiincrustantes' },
  { p: 'QDS', d: 'Desinfectantes / Biocidas' },
  { p: 'QVR', d: 'Químicos varios' },
  // P — EPP
  { p: 'PRP', d: 'Ropa de trabajo' },
  { p: 'PRS', d: 'Respiradores' },
  { p: 'PVS', d: 'Protección visual' },
  { p: 'PCP', d: 'EPP general' },
]

export const FAM_NOMBRES = {
  '1':'Galvanizado carbono', '2':'Para soldar', '3':'Epoxi',
  '4':'PVC presión', '6':'PVC cloacal / desagüe', '7':'CPVC',
  'I':'Termofusión (PPR / PE)', 'H':'Polipropileno (PP)', 'L':'Electrofusión (HDPE / PE)', 'K':'Inoxidable (piping)',
  '5':'Bulonería / Ferretería', '9':'Eléctrico', 'A':'Bombas',
  'B':'Equipos mecánicos', 'C':'Mangueras', 'E':'Chapas y metales',
  'F':'Filtración', 'G':'Tanques', 'J':'Mecánico / Accesorios',
  'N':'Herramientas', 'O':'Insumos', 'Q':'Productos Químicos', 'P':'EPP',
}
